### ISSUE TITLE
Replicated Turn In Place Rotation Fighting

### ISSUE THREAD

**Issue by MartianDays** [Cesio137/ALSReplicated#9]
Description:
Occasionally [NOT reliable in every instance] the player in a replicated game will not turn in place as far as they should [for instance, when the character should turn 180 degrees, it may jitter slightly and only turn 90 degrees or so]

Steps To Reproduce:
1: In a fresh copy of the project, run a multiplayer game of any client size, playing as client. (You may need to repeat this step until it happens.)
2: try to turn to face a direction, either by aiming or otherwise by using the looking direction turning mode.
3: Observe a very slight jitter and notice that the character [both locally and on remotes] doesn't turn as far as it should.

Expected Results:
When facing 180 degrees of the character in aim or looking direction modes in multiplayer, the player character should turn in place to face 180 degrees as it does in single-player, non-replicated games.

Actual Results:
Occasionally, the character will jitter and only turn partway - usually around 90 degrees - during a multiplayer game. The cause is unknown, and does not reliably occur in every single instance. So far happens around 50% of instances and when it does occur, lasts the duration of replicated play until terminated.

**Comment by wilberolive** [comment]
I've noticed this as well. When playing as a listen server, I find that is consistently happens with the client player, but not really with the server player. Especially in first person mode where it uses rotate in place instead of turn in place. The client does rotate/turn far enough and will slide and the rotate/turn in place animations will need to play multiple times to catch up. I could be wrong, but it almost feels like the character is not rotating fast/far enough to keep up with the animation.

**Comment by Cesio137** [comment]
@MartianDays I managed to reproduce the problem, but I could not identify the source, if anyone wants to be willing to help I also thank you.

I need to know if this problem continues after the game build, if it continues this is a problem in the project itself, otherwise it may be a small problem in the synchronization of information from the engine itself

**Comment by MartianDays** [comment]
I've noticed as well that remote clients will show your rotation correctly - however, your own rotation will not. This tells me that the problem likely exists in *how* the rotation replication is being handled.

I'm not a C++ expert so I can't really look into how you're replicating the variables, but it could be worth looking at where the replication begins and ends? For whatever event that's replicating rotation, is there a "is locally controlled" check after multicast? Typically, how I replicate is Client Set Own Vars > Replicate Vars To Server, then, Server Multicasts Vars > Checks Is Locally Controlled > Only Sets Vars If Locally Controlled Is False.

Maybe that'll help?

**Comment by Cesio137** [comment]
@MartianDays I was debugging the variables and found the following

1. Input movement amount and function can sprint, seem not to be perfectly synchronized, error of 0.01 or something like that, but this cannot be fixed since it is a latency problem to synchronize.

2. The second problem I encountered was when setting the actor rotation when the movement is very sudden. This can be improved by replacing with variavies but performance can get worse.
